language: java

sudo: false
dist: trusty

install: echo "Don't let Travis CI execute './gradlew assemble' by default"

matrix:
  include:
  - jdk: oraclejdk8
  - jdk: oraclejdk9
  - jdk: openjdk10
  - jdk: openjdk11
  - jdk: openjdk12
  - jdk: openjdk13
  - jdk: openjdk-ea
  allow_failures:
  - jdk: openjdk-ea

env:
  global:
    - secure: HU0QOLEDkYHcjX+PkicGGQ5g2L1/19V2fH13OSn82DOFlIiWmCfhSI8EG/QoWwPDp/HYQ4DH5Lo+ZEhVz5tgEultItyJ38LZJl/YYOzSAiRvTezmDdz+Cdg6SXAwCvgFCTagEJ1ChL5NyenDGDlwPB/drN0HlNNU6igPqNkM8l0=
    - secure: VByzrX+inH3Z2nq50Hkj1FJnyOjPdsdIo/RUcl6DxUjkYfXP0n3tkPZGFA0PwiDpEwvRcSGLMR7mJ59Bhja5wgqXNhMqV4F0kB2PEFHSC3UmkyMnTSmDBKvP2aT6JLq00K3mYeNV5HiaYV4S7UVNdzZwaPCgc2aVZN8hF4f5/V8=
    - secure: GWvKpGPBF1b/2tkYzJ/IwKpGd3kjfYpadIFoQOdQS3r6iZkutZ9FhW6vINIRsgcIRHTVha0BywG7m5sJIYo/jmsDbXc2VJFO7EcXkK6k96VZYb0pHjbXqeP/u9/ZfSzeQ4w3qNYUiXztmmrLjbCzG2gV4D2CqOaug2o81mVj4LI=
    - secure: m91QxOLHBRnJzRyphCivL79i90pE/FO4yg8qTOaDuyTqVXBKnHmdARFOxSMZN9Qn3B3e28xxPaazIsJGCuPXiQKSObqzPLeFHUOa3atUJSckEUW623l1313A9iMFOYbqSBAHFHmiuuAJBwN/E2OnG3BcLZV1FRibW6J1qLRLdJw=
    - secure: PNQDTaNs6UkDXsnu9cnYkc5AKoPzFaVYpL2X22Fgh/n5O/3dgxOnRqgT/CmFvEOKmh2FxD8cc19/n5j9pF11T18k7x00bfzmRLfs1B5y1KF7XdO350mOLglDJJq3XqaPELtXHBRWP+iDRcb1ggDB1jx2kUUclYeVtvT7MGTqH9jX6wI/OJhL4DVUx1gtaM7MTSujL2RyZz9rIgL1SDutKe9Dmslz6/ybrYOvN48omkEYqsKCDTdGW2o/K4lBTr2UYpqEFmJjJSEXIZWPpF7pRIVB1ybaetocaLHl8pnyybM37rzyUgUe8PY+x5oS9xnJ2u3wFg3XV0xrVLZ1w7J7Ekh8C/sS/LUv2qwBpNMHxAtKgDejCtdS2vAxSzkqxo6vuYnt8caO5KsY6GjnCSGznisuoGmEPIEvfRMMKL852cEnF21rkoQAoC1kY2WY91eNx8C9X1kv80kpVIDApS3TZ9tok7FsIUOHYuXtTfBEUAOHeqCDv42qtF1f6MfcHu2yVsjse8ZUrbJ1417BIL8E801v86W/xj7BVIHfYcR4eVV3NOcvZBL83ImXJc75Omg6qysoStv8ozXtRzX9qX51an/ZzQV0yNuWe225KaSiQppvOWOvjmv9/qXJVTPtI3HfyjSb0o6DPApHGT98rOfXbKX4tjlybY0q3mcjMe2LxlI=

cache:
  directories:
    - "$HOME/.m2/repository"
    - "$HOME/apache-maven-3.5.4"

before_install:
  - unset _JAVA_OPTIONS
  - export M2_HOME=$HOME/apache-maven-3.5.4
  - if [ ! -d $M2_HOME/bin ]; then curl https://archive.apache.org/dist/maven/maven-3/3.5.4/binaries/apache-maven-3.5.4-bin.tar.gz | tar zxf - -C $HOME; fi
  - export PATH=$M2_HOME/bin:$PATH

script: mvn -B -P ci test jacoco:report

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - mvn clean deploy -DskipTests --settings .travis/maven-settings.xml
