name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11', '17', '21', '24']
        architecture: [ 'x64' ]
      fail-fast: false
    name: Build with JDK ${{ matrix.java }} on ${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.architecture }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn test

  deploy-snapshot:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          architecture: 'x64'
          cache: 'maven'

      - name: Setup Maven Settings
        uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: '[{"id": "central", "username": "${{secrets.CENTRAL_USERNAME}}", "password": "${{secrets.CENTRAL_PASSWORD}}"}]'

      - name: Deploy Snapshot
        run: mvn deploy -DskipTests -B
